language: node_js
node_js:
  - '8'
services:
  - docker
install:
  - yarn --ignore-engines
  - yarn test
  - docker build -t turbologz/turbo-logz-user-api:$TRAVIS_BUILD_NUMBER .
deploy:
  - provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && yarn docker:tag && yarn docker:push
    on:
      branch: master